import RootStyleRegistry from './emotion';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RootStyleRegistry>
      <html lang="en">
        <body>{children}</body>
      </html>
    </RootStyleRegistry>
  );
}
